Repository szkolny-eu/szkolny-android, pull requests merged in 2021-09, with the labels that each got.

#57 [UI] Fix block timetable export.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/timetable/GenerateBlockTimetableDialog.kt
Labels: bug

#15 [UI] Add list of contributors in Settings.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/pl/szczodrzynski/edziennik/Extensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/szkolny/SzkolnyApi.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/szkolny/SzkolnyService.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/szkolny/response/ContributorsResponse.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/base/lazypager/FragmentLazyPagerAdapter.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/settings/cards/SettingsAboutCard.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/settings/contributors/ContributorsActivity.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/settings/contributors/ContributorsAdapter.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/settings/contributors/ContributorsFragment.kt
  app/src/main/res/layout/contributors_activity.xml
  app/src/main/res/layout/contributors_list_fragment.xml
  app/src/main/res/layout/contributors_list_item.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/plurals.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/plurals.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, help wanted, invalid, question

#59 [UI] Center "no data" text view.
  app/src/main/res/layout/attendance_list_fragment.xml
  app/src/main/res/layout/attendance_summary_fragment.xml
  app/src/main/res/layout/card_home_grades.xml
  app/src/main/res/layout/card_home_template.xml
  app/src/main/res/layout/grades_item_stats.xml
  app/src/main/res/layout/grades_list_fragment.xml
  app/src/main/res/layout/homework_list_fragment.xml
  app/src/main/res/layout/messages_list_fragment.xml
  app/src/main/res/layout/notifications_list_fragment.xml
  app/src/main/res/layout/template_list_fragment.xml
  app/src/main/res/layout/template_list_page_fragment.xml
Labels: bug

#60 [DB] Workaround missing event types after profile archiving.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/agenda/AgendaFragment.kt
Labels: bug

#61 [UI] Fix multiplicated day dialog in Agenda.
  app/build.gradle
Labels: bug

#62 [UI] Update drawer header background.
  app/src/main/res/drawable/header.png
  app/src/main/res/drawable/header.webp
Labels: enhancement

#63 [Mobidziennik] Fix missing linebreaks when sending messages.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeFragment.kt
Labels: bug

#64 [API/Vulcan] Fix sending messages.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/Errors.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/DataVulcan.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/hebe/VulcanHebeMain.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/hebe/VulcanHebeSendMessage.kt
  app/src/main/res/values/errors.xml
Labels: bug

#67 [API/Vulcan] Fix missing timetable entries.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/hebe/VulcanHebeTimetable.kt
Labels: bug

#65 [UI] Fix restoring header background dialog.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/settings/cards/SettingsThemeCard.kt
Labels: bug

#66 [API/Mobidziennik] Add Web timetable scrapper.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/Regexes.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/DataEdudziennik.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebExams.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebGrades.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebHomework.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebStart.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebTimetable.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/MobidziennikFeatures.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/MobidziennikData.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebTimetable.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/DataPodlasie.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiFinalGrades.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiGrades.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiMain.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiTimetable.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/models/Data.kt
Labels: enhancement

#68 [UI] Use number keyboard in the PIN field in Vulcan.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/login/LoginFormFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/login/LoginInfo.kt
Labels: enhancement

#69 [Messages] Fix downloading and displaying attachment on API 30+.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/views/AttachmentsView.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/Utils.java
  app/src/main/res/layout/message_fragment.xml
Labels: bug

#72 [API/Vulcan] Fix missing attendance.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/hebe/VulcanHebeAttendance.kt
Labels: bug

#70 [Lab] Add button to disable devmode and Chucker toggle.
  app/src/main/java/pl/szczodrzynski/edziennik/App.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/Config.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabPageFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabProfileFragment.kt
  app/src/main/res/layout/lab_fragment.xml
Labels: enhancement

#75 [API] Refactor register availability checking module.
  app/src/main/java/pl/szczodrzynski/edziennik/App.kt
  app/src/main/java/pl/szczodrzynski/edziennik/MainActivity.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/Config.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ConfigExtensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ConfigMigration.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/EdziennikTask.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/events/RegisterAvailabilityEvent.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Profile.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/firebase/SzkolnyAppFirebase.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/RegisterUnavailableDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabPageFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/home/HomeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/home/cards/HomeAvailabilityCard.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/login/LoginChooserFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/login/LoginPrizeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/managers/AvailabilityManager.kt
  app/src/main/res/layout/lab_fragment.xml
Labels: enhancement

#74 [UI] Show attendance info in timetable and lesson dialog.
  app/build.gradle
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/dao/AttendanceDao.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/timetable/LessonDetailsDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/timetable/TimetableDayFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/managers/AttendanceManager.kt
  app/src/main/res/layout/dialog_lesson_details.xml
  app/src/main/res/layout/timetable_lesson.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
