Repository szkolny-eu/szkolny-android, pull requests merged in 2021-04, with the labels that each got.

#14 README update
  .github/readme-banner.png
  README.md
Labels: enhancement

#12 Finish English translation
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#21 Add teachers' names context menus (dialogs)
  app/proguard-rules.pro
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/event/EventDetailsDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/grade/GradeDetailsDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/timetable/LessonDetailsDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/attendance/AttendanceDetailsDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/behaviour/NoticesAdapter.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/BetterLink.kt
  app/src/main/res/layout/attendance_details_dialog.xml
  app/src/main/res/layout/dialog_event_details.xml
  app/src/main/res/layout/dialog_grade_details.xml
  app/src/main/res/layout/dialog_lesson_details.xml
Labels: enhancement

#26 Update copyright date
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#29 [App] Make registerAvailability flavor-aware.
  app/src/main/java/pl/szczodrzynski/edziennik/config/ConfigSync.kt
Labels: bug

#23 Add notification icons
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/task/PostNotifications.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Notification.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/notifications/NotificationsAdapter.kt
  app/src/main/res/layout/notifications_list_item.xml
Labels: enhancement

#22 Add eggfall
  app/build.gradle
  app/src/main/java/pl/szczodrzynski/edziennik/MainActivity.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ConfigUI.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/settings/cards/SettingsThemeCard.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/BigNightUtil.kt
  app/src/main/res/drawable/egg1.webp
  app/src/main/res/drawable/egg2.webp
  app/src/main/res/drawable/egg3.webp
  app/src/main/res/drawable/egg4.webp
  app/src/main/res/drawable/egg5.webp
  app/src/main/res/drawable/egg6.webp
  app/src/main/res/layout/eggfall.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#30 [UI/Timetable] Add current time marker line.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/timetable/TimetableDayFragment.kt
  app/src/main/res/drawable/timetable_marker_triangle.xml
  app/src/main/res/layout/fragment_timetable_v2_day.xml
  app/src/main/res/layout/timetable_day_fragment.xml
Labels: enhancement

#39 [Messages] UI updates and fixes
  app/src/main/java/pl/szczodrzynski/edziennik/Extensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfigUI.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Profile.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/full/MessageFull.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/MessagesConfigDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/MessageFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/MessagesAdapter.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/MessagesFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/MessagesListFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/models/MessagesSearch.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/utils/MessagesComparator.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/utils/MessagesFilter.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/utils/SearchTextWatcher.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/viewholder/MessageViewHolder.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/viewholder/SearchViewHolder.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/settings/cards/SettingsRegisterCard.kt
  app/src/main/res/layout/messages_config_dialog.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement
