Repository szkolny-eu/szkolny-android, pull requests merged in 2021-10, with the labels that each got.

#81 [API/Mobidziennik] Implement getting full event description.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/Regexes.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/Mobidziennik.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebCalendar.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebGetEvent.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/models/Data.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/task/Notifications.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/AppDb.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/dao/MetadataDao.java
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Event.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/full/EventFull.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/migration/Migration94.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/firebase/SzkolnyAppFirebase.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/event/EventDetailsDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/debug/LabPageFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/widgets/timetable/WidgetTimetableProvider.kt
Labels: enhancement, hacktoberfest-accepted

#83 [API/Mobidziennik] Implement syncing extra lessons.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/api/MobidziennikApiTeams.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/api/MobidziennikApiTimetable.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebTimetable.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/models/DataRemoveModel.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/AppDb.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/dao/TimetableDao.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/entity/Lesson.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/migration/Migration95.kt
Labels: enhancement, hacktoberfest-accepted

#84 [API/Mobidziennik] Fix showing homework attachments.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/Regexes.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/edudziennik/data/web/EdudziennikWebGetHomework.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/data/synergia/LibrusSynergiaGetHomework.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/librus/data/synergia/LibrusSynergiaHomework.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebGetEvent.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebGetHomework.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebGetMessage.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/mobidziennik/data/web/MobidziennikWebHomework.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiEvents.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/podlasie/data/api/PodlasieApiHomework.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/Vulcan.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/MessageFragment.kt
Labels: bug, enhancement, hacktoberfest-accepted

#85 [Messages/Compose] Add text styling support.
  app/src/main/java/pl/szczodrzynski/edziennik/Extensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeChipCreator.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeChipTokenizer.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/modules/messages/compose/MessagesComposeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/TextInputKeyboardEdit.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/html/BetterHtml.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/span/BoldSpan.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/span/ImprovedBulletSpan.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/span/ItalicSpan.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/span/SubscriptSizeSpan.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/span/SuperscriptSizeSpan.kt
  app/src/main/res/layout/messages_compose_fragment.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, hacktoberfest-accepted

#114 [Lab] Add Open Chucker button.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/debug/LabPageFragment.kt
  app/src/main/res/layout/lab_fragment.xml
Labels: enhancement

#115 [Login] Fix incorrect case mode validation.
  app/src/main/java/pl/szczodrzynski/edziennik/ui/login/LoginFormFragment.kt
Labels: bug

#116 [API/Vulcan] Fix teachers endpoint last sync date.
  app/src/main/java/pl/szczodrzynski/edziennik/data/api/edziennik/vulcan/data/hebe/VulcanHebeTeachers.kt
Labels: bug
