Repository szkolny-eu/szkolny-android, pull requests merged in 2022-10, with the labels that each got.

#143 [UI] Request notifications permission on API >= 33.
  app/src/main/AndroidManifest.xml
  app/src/main/java/pl/szczodrzynski/edziennik/ui/home/HomeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/login/LoginChooserFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/managers/PermissionManager.kt
Labels: bug, enhancement, good first issue, hacktoberfest-accepted

#140 [UI/Timetable] Add Timetable settings.
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfigUI.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/dialogs/settings/TimetableConfigDialog.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/timetable/TimetableDayFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/timetable/TimetableFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/MutableLazy.kt
  app/src/main/res/layout/dialog_config_agenda.xml
  app/src/main/res/layout/timetable_config_dialog.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, hacktoberfest-accepted

#141 [UI/Timetable] Show subject-based lesson colors.
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfigUI.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/timetable/TimetableDayFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/utils/Colors.java
  app/src/main/res/layout/timetable_config_dialog.xml
  app/src/main/res/layout/timetable_lesson.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, hacktoberfest-accepted

#150 [App] Move per-register settings to JSON resource. Rewrite Config to use delegates.
  .idea/codeStyles/Project.xml
  .idea/dictionaries/Kuba.xml
  app/src/main/java/pl/szczodrzynski/edziennik/App.kt
  app/src/main/java/pl/szczodrzynski/edziennik/MainActivity.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/AbstractConfig.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/AppData.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/BaseConfig.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/Config.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ConfigGrades.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ConfigSync.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ConfigTimetable.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ConfigUI.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/DelegateConfig.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfig.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfigAttendance.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfigGrades.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfigSync.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/ProfileConfigUI.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/db/ConfigDao.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ConfigExtensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ConfigGsonUtils.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ConfigMigration.kt
  app/src/main/java/pl/szczodrzynski/edziennik/config/utils/ProfileConfigMigration.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/dao/EventTypeDao.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/enums/LoginType.kt
  app/src/main/java/pl/szczodrzynski/edziennik/data/db/enums/SchoolType.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ext/DataExtensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ext/JsonExtensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ext/MiscExtensions.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/agenda/AgendaFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/announcements/AnnouncementsFragment.java
  app/src/main/java/pl/szczodrzynski/edziennik/ui/behaviour/BehaviourFragment.java
  app/src/main/java/pl/szczodrzynski/edziennik/ui/behaviour/NoticesAdapter.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/home/HomeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/login/LoginSyncFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/messages/compose/MessagesComposeFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/messages/single/MessageFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/timetable/TimetableDayFragment.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/views/EventTypeDropdown.kt
  app/src/main/java/pl/szczodrzynski/edziennik/ui/widgets/WidgetConfigActivity.java
  app/src/main/java/pl/szczodrzynski/edziennik/ui/widgets/timetable/WidgetTimetableProvider.kt
  app/src/main/res/raw/app_data.json
  app/src/main/res/values/strings.xml
Labels: enhancement
